### ISSUE TITLE
How to get API key? 

### ISSUE THREAD

**Issue by StanislavZakharov** [zurche/beer-detector#1]
Smthing going wrong when put my API Key in code. The app crashes with error:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List LogoResponse.getResponses()' on a null object reference

One more question. In your article on Medium you say, that 'Now that I had the Vision API ready to use, I started testing it playing around encoding some images and getting some responses on what that images were' and give some screenshots. Where did yo test it? It is special program or what?

**Comment by zurche** [comment]
Hello there Stanislav, you certainly wont be able to use this app out of the box since like I also pointed out in the article Google charges you for each api request you make to its Vision API servers. So I checked in this repository with a "insert your api key here" place holder because otherwise anyone using the repository would be able to use my vision API and therefore charging my own credit card :)

Once the api key is place, this example works perfectly since its the only thing I removed. I suggest you create your own dashboard in google cloud here: https://cloud.google.com/vision/ setup your project and get a valid vision api key. 

Once you get your key, simply add it in the retrofit service of my project: https://github.com/zurche/beer-detector/blob/master/app/src/main/java/com/zurche/beerclassifier/retrofit/service/VisionApiService.java

And remember not to share it too!

Regards!

**Comment by StanislavZakharov** [comment]
Yes, I understand that API KEY should be my own. I put there my own to try your project, but it gives me an error however. Maybe I did smthing wrong in Google Cloud...My API KEY looks like:

1069232484wfwf54-frvf3h0klfliut841c5aj1wjfwjpeuf0ase7ipa.apps.googleusercontent.com
(I changed it to random to show an example)

I also enable billing and enable Vision API.

The problem is still occur. Do not know how to fix it.

**Comment by zurche** [comment]
Ok I see so, some things to check that may be producing the issue:
1. Does the camera of the device you are testing works ok?
2. Have you checked if your Google Cloud console is properly setup by sending a base64 encoded image using some HTTP request checker such as postman or ARC?

I you did both and they are both ok, whats left to check is some debugging in the IDE

**Comment by StanislavZakharov** [comment]
1. The camera of the device is OK.
2. I just check url which I send in postman and it tells me:

<!DOCTYPE html>
<html lang=en>
    <meta charset=utf-8>
    <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
    <title>Error 404 (Not Found)!!1</title>
    <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
    <a href=//www.google.com/>
    <span id=logo aria-label=Google></span>
</a>
<p>
    <b>404.</b>
    <ins>That’s an error.</ins>
    <p>The requested URL 
        <code>/v1/images:annotate/106905242784-frvo6asvssdf1k4liut841c5aj1puf0asewgefwfw7ipa.apps.googleusercontent.com</code> was not found on this server.
        <ins>That’s all we know.</ins>

So, the requested URL cannot be found on the server...Do not know what to do with it. 
Also tried to use breakpoints when debbuging app in AS. I put breakpoint in OnResponse method and I receive Log that 'Got response succesfully'.

**Comment by zurche** [comment]
So the problem maybe its related to your Google Cloud configuration since I tested with the following url:
**Type**: POST
**URL**: https://vision.googleapis.com/v1/images:annotate?key=_MY_API_KEY_HERE_
**RawPayload**:
```
{
  "requests":[
    {
      "image":{
        "content":"YOUR_BASE_64_ENCODED_IMAGE_HERE"
      },
      "features":[
        {
          "type":"LOGO_DETECTION",
          "maxResults":1
        }
      ]
    }
  ]
}
```

That should return a 200OK with the prediction of the image, if that does not work, the app wont do it either.

**Comment by StanislavZakharov** [comment]
Yes, I understand that something wrong in Google Cloud. Maybe I do not take API Key correctly.
Did you create API KEY as mentioned here? Or some else way?

**Comment by zurche** [comment]
I just followed Its own how-to's right here: https://cloud.google.com/vision/docs/common/auth

Hope that helps! And let me know if you have any issues with the app!
